version: '3.1'
services:
  meltano:
    image: meltano/meltano
    working_dir: /project
    volumes:
      - ./:/project
    ports:
      - '5000:5000'
  warehouse_db:
    image: postgres
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_USER: warehouse
    ports:
    - '5502:5432'
  source_db:
    image: robmoore/adventureworks-for-postgres
    environment:
        POSTGRES_DB: AdventureWorks
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - '5503:5432'
